# Generated by Django 4.2.3 on 2026-02-07 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DadosEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dados", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "dados da empresa",
                "verbose_name_plural": "dados das empresas",
            },
        ),
        migrations.AddField(
            model_name="cliente",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo",
            field=models.CharField(
                choices=[("PF", "Pessoa Física"), ("PJ", "Pessoa Jurídica")],
                default="PF",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Documentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("C", "Contrato"),
                            ("P", "Petição"),
                            ("CONT", "Contestação"),
                            ("R", "Recursos"),
                            ("O", "Outro"),
                        ],
                        default="O",
                        max_length=255,
                    ),
                ),
                ("arquivo", models.FileField(upload_to="documentos/")),
                ("data_upload", models.DateTimeField()),
                ("content", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento",
                "verbose_name_plural": "documentos",
            },
        ),
    ]
