# Generated by Django 4.2.3 on 2026-02-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0003_dadosempresa_cliente_status_cliente_tipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentos",
            name="data_upload",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
