# Generated by Django 4.2.3 on 2026-02-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0004_alter_documentos_data_upload"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pergunta", models.TextField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContextRag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.JSONField()),
                ("tool_name", models.CharField(max_length=255)),
                ("tool_args", models.JSONField(blank=True, null=True)),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.pergunta"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnaliseJurisprudencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indice_risco", models.IntegerField()),
                ("classificacao", models.CharField(max_length=20)),
                ("erros_coerencia", models.JSONField(default=list)),
                ("riscos_juridicos", models.JSONField(default=list)),
                ("problemas_formatacao", models.JSONField(default=list)),
                ("red_flags", models.JSONField(default=list)),
                ("tempo_processamento", models.IntegerField(default=0)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analises",
                        to="clientes.documentos",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_criacao"],
            },
        ),
    ]
